In [2]:
import xarray_behave as xb
import matplotlib.pyplot as plt
import scipy
import numpy as np
import datetime
import pandas as pd

from tools import parse_log_file

plt.style.use('ncb.mplstyle')

In [11]:
datename='localhost-20260402_130508'
root='/Volumes/agauneu/#Data/playback'
suffix = '_2' # or ''
filename = f"{datename}{suffix}"

ds = xb.assemble(datename=datename, root=root, target_sampling_rate=1_000, resample_video_data=True, filepath_poses=f"{root}/res/{datename}/{filename}_sleap.h5", filepath_video=f"{root}/res/{datename}/{filename}_sleap.h5")
nb_flies = len(ds.flies)
ds

   Failed loading movie params - no ss_movie

<xarray.Dataset> Size: 3GB
Dimensions:              (sampletime: 17995000, channels: 1, time: 3597984,
                          event_types: 0, event_time: 3, index: 0,
                          poseparts: 2, coords: 2, flies: 10)
Coordinates:
  * sampletime           (sampletime) float64 144MB 0.0 0.0002 ... 3.599e+03
  * time                 (time) float64 29MB 0.0 0.0009999 ... 3.598e+03
    nearest_frame        (time) int64 29MB 304 305 305 ... 216173 216173 216173
  * event_types          (event_types) float64 0B
    event_categories     (event_types) float64 0B
  * event_time           (event_time) <U13 156B 'start_seconds' ... 'channels'
  * poseparts            (poseparts) <U4 32B 'head' 'tail'
  * coords               (coords) <U1 8B 'y' 'x'
Dimensions without coordinates: channels, index, flies
Data variables:
    song_raw             (sampletime, channels) float64 144MB 4.02e-05 ... -0...
    song_events          (time, event_types) int16 0B
    event_times          (index, event_time) float64 0B
    event_names          (index) <U128 0B
    pose_positions       (time, flies, poseparts, coords) float64 1GB 0.0 ......
    pose_positions_allo  (time, flies, poseparts, coords) float64 1GB 629.6 ....
Attributes:
    video_filename:           /Volumes/agauneu/#Data/playback/dat/localhost-2...
    datename:                 localhost-20260402_130508
    root:                     /Volumes/agauneu/#Data/playback
    dat_path:                 dat
    res_path:                 res
    sampling_rate_Hz:         5000.0
    target_sampling_rate_Hz:  1000
    ref_time:                 1775127920.2991

### Parse logs

In [ ]:
logs = parse_log_file(f"{root}/dat/{datename}/{datename}_daq.log")
stim_names = [s[0] for s in logs['stimFileName']]
logs.head()

,timestamp,rig,cnt,stimFileName,silencePre,silencePost,delayPost,intensity,freq,MODE
0,2026-04-02 13:05:20.264,DAQ@PC-845393,1,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan]
1,2026-04-02 13:06:22.855,DAQ@PC-845393,2,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan]
2,2026-04-02 13:07:26.857,DAQ@PC-845393,3,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan]
3,2026-04-02 13:08:30.860,DAQ@PC-845393,4,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan]
4,2026-04-02 13:09:34.862,DAQ@PC-845393,5,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan]

### Compute speed

In [5]:
pos = np.nanmean(ds.pose_positions_allo, axis=-2)
speed_raw = np.linalg.norm(xb.metrics.velocity(pos), axis=-1)
speed = scipy.signal.medfilt(speed_raw, 5)

/var/folders/zr/6ql4dzjx0tq8mpzht_2dwh480000gn/T/ipykernel_3142/3299271039.py:1: RuntimeWarning: Mean of empty slice
  pos = np.nanmean(ds.pose_positions_allo, axis=-2)

### Detect stimulus on and offsets

In [6]:
fs = ds.attrs['target_sampling_rate_Hz']
win_len = int(0.05 * fs)
window = scipy.signal.windows.gaussian(win_len, win_len // 8)
window /= np.sum(window)

env = np.sqrt(np.convolve(ds.song_raw[:, 0]**2, window, mode='full'))
env = env[win_len//2:win_len//2 + ds.song_raw.shape[0]]

In [7]:
thres = 1
stim = scipy.ndimage.binary_closing(env>thres, np.ones(1001))
stim_diff = np.diff(stim, prepend=0).astype(float)
stim_onsets = np.where(stim_diff==1)[0]
stim_offsets = np.where(stim_diff==-1)[0]

onset_times = ds.sampletime[stim_onsets]
offset_times = ds.sampletime[stim_offsets]

In [8]:
fs = ds.attrs['target_sampling_rate_Hz']
prefix = int(5 * fs)
duration = int(10 * fs)

all_traces = np.zeros((len(stim_onsets), prefix + duration, nb_flies))
for cnt, onset_time in enumerate(onset_times):
    onset_idx = np.argmax(ds.time.data[:, np.newaxis]>=onset_time.data)
    all_traces[cnt, :, :] = speed[onset_idx - prefix:onset_idx + duration, :]

all_traces = np.array(all_traces)

In [ ]:
time = np.arange(-prefix, duration) / fs
time

array([-5.   , -4.999, -4.998, ...,  9.997,  9.998,  9.999],
      shape=(15000,))

In [38]:
logs = logs.iloc[:len(onset_times)]
logs['onset_times'] = np.asarray(onset_times)
logs['offset_times'] = np.asarray(offset_times)

logs

,timestamp,rig,cnt,stimFileName,silencePre,silencePost,delayPost,intensity,freq,MODE,onset_times,offset_times
0,2026-04-02 13:05:20.264,DAQ@PC-845393,1,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],30.974386,34.909551
1,2026-04-02 13:06:22.855,DAQ@PC-845393,2,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],94.965852,98.933078
2,2026-04-02 13:07:26.857,DAQ@PC-845393,3,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],158.958287,162.743515
3,2026-04-02 13:08:30.860,DAQ@PC-845393,4,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],222.860700,226.796922
4,2026-04-02 13:09:34.862,DAQ@PC-845393,5,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],286.853649,290.820875
5,2026-04-02 13:10:38.864,DAQ@PC-845393,6,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],350.846057,354.631278
6,2026-04-02 13:11:42.667,DAQ@PC-845393,7,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],414.748456,418.683681
7,2026-04-02 13:12:46.669,DAQ@PC-845393,8,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],478.740856,482.708081
8,2026-04-02 13:13:50.671,DAQ@PC-845393,9,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],542.732825,546.518546
9,2026-04-02 13:14:54.674,DAQ@PC-845393,10,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],606.635198,610.570967
10,2026-04-02 13:15:58.677,DAQ@PC-845393,11,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],670.627568,674.594789
11,2026-04-02 13:17:02.679,DAQ@PC-845393,12,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],734.619938,738.405160
12,2026-04-02 13:18:06.482,DAQ@PC-845393,13,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],798.522296,802.457519
13,2026-04-02 13:19:10.484,DAQ@PC-845393,14,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],862.514637,866.481858
14,2026-04-02 13:20:14.486,DAQ@PC-845393,15,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],926.506976,930.292452
15,2026-04-02 13:21:18.289,DAQ@PC-845393,16,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],990.409316,994.345227
16,2026-04-02 13:22:22.291,DAQ@PC-845393,17,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1054.402014,1058.369204
17,2026-04-02 13:23:26.293,DAQ@PC-845393,18,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],1118.393975,1122.180193
18,2026-04-02 13:24:30.296,DAQ@PC-845393,19,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1182.296394,1186.231613
19,2026-04-02 13:25:34.297,DAQ@PC-845393,20,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1246.288591,1250.256601
20,2026-04-02 13:26:38.300,DAQ@PC-845393,21,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],1310.280905,1314.067121
21,2026-04-02 13:27:42.102,DAQ@PC-845393,22,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1374.184084,1378.119432
22,2026-04-02 13:28:46.105,DAQ@PC-845393,23,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1438.176465,1442.143684
23,2026-04-02 13:29:50.107,DAQ@PC-845393,24,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],1502.167867,1505.953972
24,2026-04-02 13:30:54.109,DAQ@PC-845393,25,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1566.071042,1570.006260
25,2026-04-02 13:31:58.112,DAQ@PC-845393,26,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1630.063330,1634.030550
26,2026-04-02 13:33:02.114,DAQ@PC-845393,27,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],1694.055612,1697.840828
27,2026-04-02 13:34:05.916,DAQ@PC-845393,28,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1757.957773,1761.893097
28,2026-04-02 13:35:09.918,DAQ@PC-845393,29,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1821.950148,1825.917366
29,2026-04-02 13:36:13.921,DAQ@PC-845393,30,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],1885.942418,1889.727633
30,2026-04-02 13:37:17.723,DAQ@PC-845393,31,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],1949.844589,1953.779597
31,2026-04-02 13:38:21.726,DAQ@PC-845393,32,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2013.836780,2017.804181
32,2026-04-02 13:39:25.728,DAQ@PC-845393,33,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],2077.828808,2081.614144
33,2026-04-02 13:40:29.730,DAQ@PC-845393,34,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2141.731038,2145.666186
34,2026-04-02 13:41:33.732,DAQ@PC-845393,35,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2205.723477,2209.690714
35,2026-04-02 13:42:37.735,DAQ@PC-845393,36,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],2269.715284,2273.501187
36,2026-04-02 13:43:41.537,DAQ@PC-845393,37,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2333.617963,2337.553322
37,2026-04-02 13:44:45.539,DAQ@PC-845393,38,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2397.610255,2401.577420
38,2026-04-02 13:45:49.542,DAQ@PC-845393,39,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],2461.602214,2465.387796
39,2026-04-02 13:46:53.543,DAQ@PC-845393,40,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2525.504388,2529.439778
40,2026-04-02 13:47:57.547,DAQ@PC-845393,41,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2589.497128,2593.464420
41,2026-04-02 13:49:01.548,DAQ@PC-845393,42,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],2653.489319,2657.274926
42,2026-04-02 13:50:05.351,DAQ@PC-845393,43,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2717.391503,2721.327147
43,2026-04-02 13:51:09.353,DAQ@PC-845393,44,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2781.383629,2785.350839
44,2026-04-02 13:52:13.355,DAQ@PC-845393,45,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],2845.375834,2849.161045
45,2026-04-02 13:53:17.157,DAQ@PC-845393,46,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2909.278028,2913.213240
46,2026-04-02 13:54:21.160,DAQ@PC-845393,47,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],2973.270681,2977.237894
47,2026-04-02 13:55:25.161,DAQ@PC-845393,48,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],3037.262867,3041.048079
48,2026-04-02 13:56:29.163,DAQ@PC-845393,49,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],3101.165051,3105.100265
49,2026-04-02 13:57:33.166,DAQ@PC-845393,50,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],3165.157239,3169.124448
50,2026-04-02 13:58:37.168,DAQ@PC-845393,51,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],3229.149413,3232.934584
51,2026-04-02 13:59:40.970,DAQ@PC-845393,52,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],3293.051587,3296.986798
52,2026-04-02 14:00:44.972,DAQ@PC-845393,53,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],3357.043760,3361.010971
53,2026-04-02 14:01:48.974,DAQ@PC-845393,54,[santune_ipi130_pulseTrain_PDUR30ms_PCAR170hz_...,[30000],[30000],[0],[6.0],[200.0],[nan],3421.035933,3424.821141
54,2026-04-02 14:02:52.976,DAQ@PC-845393,55,[santune_ipi70_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],3484.938104,3488.873313
55,2026-04-02 14:03:56.979,DAQ@PC-845393,56,[santune_ipi38_pulseTrain_PDUR30ms_PCAR170hz_P...,[30000],[30000],[0],[6.0],[200.0],[nan],3548.930263,3552.897474

In [39]:
save_file_name = f'{root}/res/{datename}/{filename}_spd.npz'
np.savez(save_file_name, traces=all_traces, time=time, **{k: list(v) for k, v in logs.items()})